### ISSUE TITLE
Seems to fail silently?

### ISSUE THREAD

**Issue by rruckley** [aprimadi/influxdb2#10]
I know this is still alpha code but trying to do a write, everything appears to work, code connects to InfluxDB, but there's nothing in the bucket, so I'm perplexed as to where it's going or what's happening. If it thew an error I would have somewhere to start.

Using InfluxDB 2.4.0 for reference. I have code on Github but currently in private repo.

**Comment by Samiisd** [comment]
Hi, I faced a similar issue, could you have a look at: https://github.com/aprimadi/influxdb2/issues/6, please?
I think the root cause for that is this lib considers a request as valid as long as it returns `200` (check using request.is_ok() -> check if code in range [200, 300[ ).

But some API endpoints in influxdb only have one valid HTTP response code, others often being "undefined": have a look at https://github.com/aprimadi/influxdb2/pull/9 for an example (summary, 200 is error, 204 is ok)

So what you should do I think is:
1. log the response code your getting for your query (is it 200? is it 201? ...)
2. check in influxdb/api2 doc, what should be the response code exactly & compare

**Comment by rruckley** [comment]
Issue seems to have gone away, might have been environmental. Working fine now.
