### ISSUE TITLE
DataPoint should implement clone

### ISSUE THREAD

**Issue by blueForestIcarus** [aprimadi/influxdb2#4]

**Comment by Samiisd** [comment]
Hi, facing similar issue. I think it should either implement clone, or `Client::write` method should take a ref instead of ownership.

My use case is the following: I have a DataPoints accumulator that is built up over time and flushed once certain size is reached through batch-write, the data is stored in a Vec[DataPoint]. But that behavior cannot be implemented if DataPoint is not clonable (as vec cannot be cloned), or if write cannot take a ref and forces ownership.

Also, thanks to the dev for developing and maintaining this lib !! :)

**Comment by aprimadi** [comment]
Fixed in version 0.3.1

Thank you for opening the issue and explaining the use case.
